services:
  postgres:
    image: postgres:16-alpine
    container_name: chatto_db
    volumes:
      - ./server/db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chatto
  
  adminer:
    image: adminer:4
    container_name: chatto_adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  db_data:
